"""Types for :mod:`one_link_native.chunk`."""

from collections.abc import Iterator
from typing import final
from typing_extensions import Buffer

CDC_MIN_SIZE: int
CDC_AVG_SIZE: int
CDC_MAX_SIZE: int
AEAD_FRAME_PLAINTEXT_LEN: int
AEAD_TAG_LEN: int

@final
class Boundary:
    @property
    def start(self) -> int: ...
    @property
    def end(self) -> int: ...
    @property
    def length(self) -> int: ...
    @property
    def raw_address(self) -> bytes: ...
    def raw_address_hex(self) -> str: ...
    def __repr__(self) -> str: ...

@final
class FormatBoundary:
    @property
    def start(self) -> int: ...
    @property
    def end(self) -> int: ...
    @property
    def length(self) -> int: ...
    @property
    def format_forced(self) -> bool: ...
    @property
    def raw_address(self) -> bytes: ...
    def raw_address_hex(self) -> str: ...
    def __repr__(self) -> str: ...

@final
class BoundaryIterator(Iterator[Boundary]):
    def __iter__(self) -> BoundaryIterator: ...
    def __next__(self) -> Boundary: ...
    def __len__(self) -> int: ...

def cdc_iter(obj: Buffer) -> BoundaryIterator: ...
def cdc_file(path: str) -> list[Boundary]: ...
def format_aware_boundaries(obj: Buffer, format_name: str) -> list[FormatBoundary]: ...
def chunk_address_raw(obj: Buffer) -> bytes: ...
def chunk_address_convergent(obj: Buffer) -> bytes: ...
def derive_aead_key(ratchet_chain_key: bytes, chunk_id_full: bytes) -> bytes: ...
def derive_ratchet_key_id(ratchet_chain_key: bytes, chunk_id_full: bytes) -> bytes: ...
def derive_stripe_seed(chunk_id_full: bytes, stripe_k: int) -> tuple[int, int]: ...
def frame_count(plaintext_len: int) -> int: ...
